repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
